
-- Delete tables
-- DROP TABLE IF EXISTS user_personal_data;
-- DROP TABLE IF EXISTS user_bio_data;
-- DROP TABLE IF EXISTS account;
-- DROP TABLE IF EXISTS "users";
-- DROP TABLE IF EXISTS water_intake;
-- DROP TABLE IF EXISTS activity;
-- DROP TABLE IF EXISTS exercise;
-- DROP TABLE IF EXISTS workout_plan;
-- DROP TABLE IF EXISTS workout_day;
-- DROP TABLE IF EXISTS meal_type;
-- DROP TABLE IF EXISTS meal_plan;
-- DROP TABLE IF EXISTS favourite;
-- DROP TABLE IF EXISTS recipe;
-- DROP TABLE IF EXISTS recipe_user;
-- DROP TABLE IF EXISTS activity_user;
-- DROP TABLE IF EXISTS meal_plan_meal_type;
-- DROP TABLE IF EXISTS meal_plan_user;
-- DROP TABLE IF EXISTS workout_day_exercise;
-- DROP TABLE IF EXISTS workout_day_plan;
-- DROP TABLE IF EXISTS workout_plan_user;
-- DROP TABLE IF EXISTS water_intake_user;
