version: '3'
services:
  web:
    build: .
    ports:
      - "8000:5000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGREST_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}
      DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS}
      MAXCONWAITINGTIME: ${MAXCONWAITINGTIME}
      DB_MAX_LIFETIME_CONNECTIONS: ${DB_MAX_LIFETIME_CONNECTIONS}
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
    ports:
      - "6379:6379"
