# fly.toml app configuration file generated for dry-river-6740 on 2023-08-14T19:45:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dry-river-6740"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
