# fly.toml app configuration file generated for dark-dew-6412 on 2023-08-16T15:33:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-dew-6412"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
