// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/activities": {
            "get": {
                "description": "get activities",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Show all activities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/activity.Activity"
                            }
                        }
                    }
                }
            }
        },
        "/activities/id/{id}": {
            "get": {
                "description": "Get activity by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Show all activity by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Activity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/activity.Activity"
                            }
                        }
                    }
                }
            }
        },
        "/activities/name/{name}": {
            "get": {
                "description": "Get activities by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Show all activities by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/activity.Activity"
                            }
                        }
                    }
                }
            }
        },
        "/activities/start/session/id/{id}": {
            "post": {
                "description": "Stop Activity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Stop activity timer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Activity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/activity.ExerciseSession"
                            }
                        }
                    }
                }
            }
        },
        "/activities/user/exercises/user/{user_id}": {
            "post": {
                "description": "Get exercise session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Get user exercise session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Activity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/activity.ExerciseSession"
                            }
                        }
                    }
                }
            }
        },
        "/activities/user/session/total/stats/{user_id}": {
            "post": {
                "description": "Get user exercise total data for durations and calories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Get user exercise data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Activity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/activity.ExerciseSession"
                            }
                        }
                    }
                }
            }
        },
        "/activities/user/session/total/user/{user_id}": {
            "post": {
                "description": "Get user exercise total data for durations and calories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Get user exercise data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Activity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/activity.ExerciseSession"
                            }
                        }
                    }
                }
            }
        },
        "/exercises": {
            "get": {
                "description": "Get all exercises",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts exercises"
                ],
                "summary": "GetExercises",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.Exercises"
                            }
                        }
                    }
                }
            }
        },
        "/exercises/workout/plan": {
            "get": {
                "description": "Retrieve all workout plans",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Get workout plan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.WorkoutPlan"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new workout plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Create workout plan",
                "responses": {}
            }
        },
        "/exercises/workout/plan/exercise": {
            "get": {
                "description": "Get exercises from workout plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Get exercises from workout plan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.WorkoutPlan"
                            }
                        }
                    }
                }
            }
        },
        "/exercises/workout/plan/exercise/{id}": {
            "get": {
                "description": "Get exercises by id from workout plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Get exercises by id from workout plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.WorkoutPlan"
                            }
                        }
                    }
                }
            }
        },
        "/exercises/workout/plan/{id}": {
            "get": {
                "description": "Retrieve workout plan by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Get workout plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.WorkoutPlan"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete workout plan by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Delete workout plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.WorkoutPlan"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update workout plan by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Update workout plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.WorkoutPlan"
                            }
                        }
                    }
                }
            }
        },
        "/exercises/workout/plan/{workoutPlanID}/day/{workoutDay}/exercise/{exerciseID}": {
            "post": {
                "description": "Insert new exercise into workout plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Insert new exercise into workout plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "workout_plan_id",
                        "name": "workoutPlanID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Day",
                        "name": "workoutDay",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "exercise_id",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.WorkoutPlan"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete exercises by id from workout plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Delete exercises by id from workout plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "workout_plan_id",
                        "name": "workoutPlanID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Day",
                        "name": "workoutDay",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "exercise_id",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/exercises/workout/plan/{workoutPlanID}/day/{workoutDay}/exercise/{prevExerciseID}/{exerciseID}": {
            "patch": {
                "description": "Update exercise into workout plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Update exercise into workout plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout plan ID",
                        "name": "workoutPlanID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Day",
                        "name": "workoutDay",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "prevExerciseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/exercises/{id}": {
            "get": {
                "description": "Get exercise by its id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts exercises"
                ],
                "summary": "GetExerciseByID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.Exercises"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Insert a new exercise on the list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts exercises"
                ],
                "summary": "Insert exercise",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.Exercises"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an exercise on the list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts exercises"
                ],
                "summary": "Delete exercise",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.Exercises"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an exercise on the list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts exercises"
                ],
                "summary": "Update exercise",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workouts.Exercises"
                            }
                        }
                    }
                }
            }
        },
        "/plan/{id}": {
            "get": {
                "description": "Get diet macros",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "macros calculator"
                ],
                "summary": "Get diet macros",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uuid formatted ID.",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/calculator.UserMacroDistribution"
                            }
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get the user's info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.UserSession"
                        }
                    }
                }
            }
        },
        "/users/sign-in": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Sign in a user",
                "parameters": [
                    {
                        "description": "The user's email and password",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.signInRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.SuccessResponse"
                        },
                        "headers": {
                            "Authorization": {
                                "type": "string",
                                "description": "contains the session id in bearer format"
                            }
                        }
                    }
                }
            }
        },
        "/users/sign-out": {
            "get": {
                "description": "Delete current user session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Delete user session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sessionId string",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/auth.UserSession"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Sign out a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/users/sign-up": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Sign up a user",
                "parameters": [
                    {
                        "description": "The user's first name, last name, email, and password",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.userRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.signUpSuccessResponse"
                        },
                        "headers": {
                            "Authorization": {
                                "type": "string",
                                "description": "contains the session id in bearer format"
                            }
                        }
                    }
                }
            }
        },
        "/users/user/info": {
            "get": {
                "description": "Get info about user session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Get user session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "session string",
                        "name": "session",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/auth.UserSession"
                            }
                        }
                    }
                }
            }
        },
        "/waistline": {
            "get": {
                "description": "Get user waist line list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements waistline"
                ],
                "summary": "Get user waist line list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaistLine"
                        }
                    }
                }
            },
            "post": {
                "description": "Get user waist line",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements waistline"
                ],
                "summary": "Get user waist line",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaistLine"
                        }
                    }
                }
            }
        },
        "/waistline/{id}": {
            "get": {
                "description": "Get user waist line",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements waistline"
                ],
                "summary": "Get user waist line",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "WaistLine",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaistLine"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete user waist line",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements waistline"
                ],
                "summary": "Delete user waist line",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "WaistLine",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaistLine"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update user waist line",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements waistline"
                ],
                "summary": "Update user waist line",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "WaistLine",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaistLine"
                        }
                    }
                }
            }
        },
        "/water": {
            "get": {
                "description": "Get user water intake list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements water"
                ],
                "summary": "Get user water intake list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaterIntake"
                        }
                    }
                }
            },
            "post": {
                "description": "Insert user water intake",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements water"
                ],
                "summary": "Insert user water intake",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Water",
                        "name": "w",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaterIntake"
                        }
                    }
                }
            }
        },
        "/water/{id}": {
            "get": {
                "description": "Get user water intake",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements water"
                ],
                "summary": "Get user water intake",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Water",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaterIntake"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete user water intake",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements water"
                ],
                "summary": "Delete user water intake",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Water",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaterIntake"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update user water intake",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements water"
                ],
                "summary": "Update user water intake",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Water",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.WaterIntake"
                        }
                    }
                }
            }
        },
        "/weight": {
            "post": {
                "description": "Insert user weight",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements weight"
                ],
                "summary": "Insert user weight",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Weight",
                        "name": "w",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/measurement.Weight"
                        }
                    }
                }
            }
        },
        "/weight/{id}": {
            "get": {
                "description": "Get user weight",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements weight"
                ],
                "summary": "Get user weight",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Weight",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/measurement.Weight"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete user weight",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements weight"
                ],
                "summary": "Delete user weight",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Weight ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/measurement.Weight"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update user weight",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements weight"
                ],
                "summary": "Update user weight",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Weight ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/measurement.Weight"
                            }
                        }
                    }
                }
            }
        },
        "/weights": {
            "get": {
                "description": "Get all user weight list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements weight"
                ],
                "summary": "Get all user weight list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/measurement.Weight"
                            }
                        }
                    }
                }
            }
        },
        "/{user_id}": {
            "get": {
                "description": "Get all diet macros from user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "macros calculator"
                ],
                "summary": "Get all diet macros from user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/calculator.UserMacroDistribution"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create all diet macros from user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "macros calculator"
                ],
                "summary": "Create all diet macros from user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/calculator.UserMacroDistribution"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "activity.Activity": {
            "type": "object",
            "properties": {
                "calories_per_hour": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "duration_minutes": {
                    "type": "number"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "name": {
                    "type": "string"
                },
                "total_calories": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "activity.ExerciseSession": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "type": "integer"
                },
                "calories_burned": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "duration_hours": {
                    "type": "integer"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "duration_seconds": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "session_name": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "auth.UserSession": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "calculator.UserMacroDistribution": {
            "type": "object",
            "properties": {
                "activity": {
                    "type": "string"
                },
                "activity_description": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                },
                "bmr": {
                    "type": "integer"
                },
                "calories_distribution": {
                    "type": "string"
                },
                "calories_distribution_description": {
                    "type": "string"
                },
                "carbs": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "fats": {
                    "type": "integer"
                },
                "gender": {
                    "type": "string"
                },
                "goal": {
                    "type": "integer"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "objective": {
                    "type": "string"
                },
                "objective_description": {
                    "type": "string"
                },
                "protein": {
                    "type": "integer"
                },
                "system": {
                    "type": "string"
                },
                "tdee": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "measurement.WaistLine": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "quantity": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "measurement.WaterIntake": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "quantity": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "measurement.Weight": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "weight_value": {
                    "type": "number"
                }
            }
        },
        "user.SuccessResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "user.signInRequestBody": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "user.signUpSuccessResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "user.userRequestBody": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 48,
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "workouts.Exercises": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "custom_created": {
                    "type": "boolean"
                },
                "difficulty": {
                    "type": "string"
                },
                "equipment": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "instructions": {
                    "type": "string"
                },
                "muscle": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "video": {
                    "type": "string"
                }
            }
        },
        "workouts.WorkoutPlan": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "notes": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "workoutDays": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workouts.WorkoutPlanDay"
                    }
                }
            }
        },
        "workouts.WorkoutPlanDay": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workouts.Exercises"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "StayHealthy Swagger Documentation",
	Description:      "Alpha server built with Go and Chi",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
