basePath: /
definitions:
  auth.UserSession:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  user.SuccessResponse:
    properties:
      success:
        type: boolean
    type: object
  user.signInRequestBody:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  user.signUpSuccessResponse:
    properties:
      id:
        type: integer
    type: object
  user.userRequestBody:
    properties:
      email:
        type: string
      password:
        maxLength: 48
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Alpha server built with Go and Chi
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: StayHealthy Swagger Documentation
  version: "2.0"
paths:
  /users/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.UserSession'
      security:
      - ApiKeyAuth: []
      summary: Get the user's info
      tags:
      - users
  /users/sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: The user's email and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.signInRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Authorization:
              description: contains the session id in bearer format
              type: string
          schema:
            $ref: '#/definitions/user.SuccessResponse'
      summary: Sign in a user
      tags:
      - users
  /users/sign-out:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.SuccessResponse'
      summary: Sign out a user
      tags:
      - users
  /users/sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: The user's first name, last name, email, and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.userRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Authorization:
              description: contains the session id in bearer format
              type: string
          schema:
            $ref: '#/definitions/user.signUpSuccessResponse'
      summary: Sign up a user
      tags:
      - users
schemes:
- http
swagger: "2.0"
