basePath: /
definitions:
  activity.Activity:
    properties:
      calories_per_hour:
        type: number
      created_at:
        type: string
      duration_minutes:
        type: number
      id:
        example: "0"
        type: string
      name:
        type: string
      total_calories:
        type: number
      updated_at:
        type: string
      user_id:
        $ref: '#/definitions/sql.NullString'
    type: object
  activity.ExerciseSession:
    properties:
      activity_id:
        type: integer
      calories_burned:
        type: integer
      created_at:
        type: string
      duration_hours:
        type: integer
      duration_minutes:
        type: integer
      duration_seconds:
        type: integer
      end_time:
        type: string
      id:
        example: ""
        type: string
      session_name:
        type: string
      start_time:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  auth.UserSession:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  calculator.UserMacroDistribution:
    properties:
      activity:
        type: string
      activity_description:
        type: string
      age:
        type: integer
      bmr:
        type: integer
      calories_distribution:
        type: string
      calories_distribution_description:
        type: string
      carbs:
        type: integer
      created_at:
        type: string
      fats:
        type: integer
      gender:
        type: string
      goal:
        type: integer
      height:
        type: integer
      id:
        example: ""
        type: string
      objective:
        type: string
      objective_description:
        type: string
      protein:
        type: integer
      system:
        type: string
      tdee:
        type: integer
      user_id:
        type: integer
      weight:
        type: integer
    type: object
  sql.NullString:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
  user.SuccessResponse:
    properties:
      success:
        type: boolean
    type: object
  user.signInRequestBody:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  user.signUpSuccessResponse:
    properties:
      id:
        type: integer
    type: object
  user.userRequestBody:
    properties:
      email:
        type: string
      password:
        maxLength: 48
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Alpha server built with Go and Chi
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: StayHealthy Swagger Documentation
  version: "2.0"
paths:
  /{user_id}:
    get:
      consumes:
      - application/json
      description: Get all diet macros from user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/calculator.UserMacroDistribution'
            type: array
      summary: Get all diet macros from user
      tags:
      - macros calculator
    post:
      consumes:
      - application/json
      description: Create all diet macros from user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/calculator.UserMacroDistribution'
            type: array
      summary: Create all diet macros from user
      tags:
      - macros calculator
  /activities:
    get:
      consumes:
      - application/json
      description: get activities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/activity.Activity'
            type: array
      summary: Show all activities
      tags:
      - activities
  /activities/id/{id}:
    get:
      consumes:
      - application/json
      description: Get activity by id
      parameters:
      - description: Activity ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/activity.Activity'
            type: array
      summary: Show all activity by id
      tags:
      - activities
  /activities/name/{name}:
    get:
      consumes:
      - application/json
      description: Get activities by name
      parameters:
      - description: Activity Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/activity.Activity'
            type: array
      summary: Show all activities by name
      tags:
      - activities
  /activities/start/session/id/{id}:
    post:
      consumes:
      - application/json
      description: Stop Activity
      parameters:
      - description: Activity ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/activity.ExerciseSession'
            type: array
      summary: Stop activity timer
      tags:
      - activities
  /activities/user/exercises/user/{user_id}:
    post:
      consumes:
      - application/json
      description: Get exercise session
      parameters:
      - description: Activity ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/activity.ExerciseSession'
            type: array
      summary: Get user exercise session
      tags:
      - activities
  /activities/user/session/total/stats/{user_id}:
    post:
      consumes:
      - application/json
      description: Get user exercise total data for durations and calories
      parameters:
      - description: Activity ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/activity.ExerciseSession'
            type: array
      summary: Get user exercise data
      tags:
      - activities
  /activities/user/session/total/user/{user_id}:
    post:
      consumes:
      - application/json
      description: Get user exercise total data for durations and calories
      parameters:
      - description: Activity ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/activity.ExerciseSession'
            type: array
      summary: Get user exercise data
      tags:
      - activities
  /plan/{id}:
    get:
      consumes:
      - application/json
      description: Get diet macros
      parameters:
      - description: uuid formatted ID.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/calculator.UserMacroDistribution'
            type: array
      summary: Get diet macros
      tags:
      - macros calculator
  /users/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.UserSession'
      security:
      - ApiKeyAuth: []
      summary: Get the user's info
      tags:
      - users
  /users/sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: The user's email and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.signInRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Authorization:
              description: contains the session id in bearer format
              type: string
          schema:
            $ref: '#/definitions/user.SuccessResponse'
      summary: Sign in a user
      tags:
      - users
  /users/sign-out:
    get:
      consumes:
      - application/json
      description: Delete current user session
      parameters:
      - description: sessionId string
        in: path
        name: sessionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/auth.UserSession'
            type: array
      summary: Delete user session
      tags:
      - session
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.SuccessResponse'
      summary: Sign out a user
      tags:
      - users
  /users/sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: The user's first name, last name, email, and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.userRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Authorization:
              description: contains the session id in bearer format
              type: string
          schema:
            $ref: '#/definitions/user.signUpSuccessResponse'
      summary: Sign up a user
      tags:
      - users
  /users/user/info:
    get:
      consumes:
      - application/json
      description: Get info about user session
      parameters:
      - description: session string
        in: path
        name: session
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/auth.UserSession'
            type: array
      summary: Get user session
      tags:
      - session
schemes:
- http
swagger: "2.0"
