name: Main testing workflow

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master,main]
  schedule:
    - cron '0 0 * * 0'

#defaults:
#  run:
#    working-directory:
#
#env:
#  TOKEN_NAME: ${{TOKEN_NAME}}

#on:
#  release:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
          cache-dependency-path: go.sum

#      maybe delete later
      - name: clean packages
        run: make clean-packages

      - name: install requirements
        run: make requirements

      - name: run swagger
        run: swag init
      - name: run tests
        run: go test

      - name: upload tests
        uses: actions/upload-artifact@v2
        with:
            name: test-results
            path: |

      - run: go run main.go
